### ISSUE TITLE
Bug: Clicking follow button on community user card navigates to user page

### ISSUE THREAD

**Issue by carbontwelve** [Goldfish-Social/Goldfish#10]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/464699/183941895-1c9a234a-18f1-49ab-b1d6-81a815cfccae.png">

On the page https://goldfish.social/community

When clicking on the follow button as shown in the above image, rather than the expected behaviour of executing the follow action, the user is unexpectedly navigated to the user's profile page (in this case https://goldfish.social/@stux)

**Comment by mstdn** [comment]
Known! I made this for that :-)
https://github.com/Goldfish-Social/Goldfish/issues/6
