### ISSUE TITLE
user profile urls aren't clickable nor can be seen

### ISSUE THREAD

**Issue by FillingTheVoidOnYT** [Goldfish-Social/Goldfish#17]
when looking at an users profile the url attached to it can't be clicked or can be seen. It's cut off half way as shown in the screenshot below
![Screenshot from 2022-08-18 20-10-23](https://user-images.githubusercontent.com/110159004/185534829-24e65d13-4cab-43e3-bb85-40b15239359c.png)

**Comment by mstdn** [comment]
Fixed! https://github.com/Goldfish-Social/Goldfish/commit/3a541c1a28541771724536f5066dd97952166675
