### ISSUE TITLE
Web ToS is inconsistent with project license

### ISSUE THREAD

**Issue by CONIGUERO** [Goldfish-Social/Goldfish#30]
The web's Term of Service state that:

> Permission is granted to temporarily download one copy of the materials on Goldfish.Social's Website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:

> modify or copy the materials;
use the materials for any commercial purpose or for any public display;
> attempt to reverse engineer any software contained on Goldfish.Social's Website;
> remove any copyright or other proprietary notations from the materials; or
> transferring the materials to another person or "mirror" the materials on any other server.

This is clearly contradictory to the project's license (AGPL) on its repo, where copying, modification, redistribution and reverse engineering/source code derivation are allowed. (And in the case of source code derivation, *mandated*)

**Comment by mstdn** [comment]
Thank you! Fixed in [28a08b9e924a12df421b0fc7bc0537297e12cb19](https://github.com/Goldfish-Social/Goldfish/commit/28a08b9e924a12df421b0fc7bc0537297e12cb19)
