### ISSUE TITLE
Setup a guide for translation contribution

### ISSUE THREAD

**Issue by Penfore** [Goldfish-Social/Goldfish#41]
I would like to contribute with translations to Brazilian Portuguese.

Please, consider adding a guide to this type of contributions.

**Comment by le-jun** [comment]
I think localization is still a stub at this point, it seems one could translate the whole thing through [this directory](https://github.com/Goldfish-Social/Goldfish/tree/main/lang):

* Create a folder for your language using the 2 letters code
* Copy and modify the content of the `en` folder
* Pull Request.
