### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by mstdn** [Goldfish-Social/Goldfish#7]
Add PWA support.

**Comment by ppnplus** [comment]
I’d also like to see the instructions for users to add the PWA to their home screen and use it like an app “without taking up storage space”, right in the web UI itself.

**Comment by FillingTheVoidOnYT** [comment]
pwa support would be nice

**Comment by mstdn** [comment]
PWA added! 🥳 
https://github.com/Goldfish-Social/Goldfish/commit/6e5365177c9534ba4368616fa85318631d805d88
